title: CS 489/698
description: The CS 489/698 course website at the University of Waterloo. 
theme: just-the-docs

url: https://uw-sec.github.io/secprog/

$pink-000: #f77ef1;

aux_links:
  LEARN: https://github.com/just-the-docs/just-the-docs-template
  ED:    https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  highlight:
    title: Highlight
    color: yellow
  new:
    title: New
    color: green

# Collections for website data
collections:
  modules:
  schedules:

# Default layouts for each collection type
defaults:
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule

liquid:
  error_mode: strict
  strict_filters: true